# Generated by Django 3.0.6 on 2020-05-18 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField(default=datetime.datetime.now)),
                ('qualification', models.CharField(max_length=20)),
                ('tech_skills', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=50)),
            ],
        ),
    ]
